apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
spec:
  objectStorage:
    externalStorage:
      host: minio-service.mlops-team-a.svc
