apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: nfs-csi
