apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-chains-root
  namespace: openshift-gitops
spec:
  project: mlops
  source:
    repoURL: https://github.com/acicfede/mlops-chains.git
    targetRevision: main
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

