apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redb-my-doc
  namespace: cyberark-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: cyberark-sm
    kind: SecretStore
  target:
    name: redb-my-doc
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: data/vault/secrets-safe/Generic/username
    - secretKey: password
      remoteRef:
        key: data/vault/secrets-safe/Generic/password
