apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: external-secrets-operator
  namespace: cyberark-demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: alpha
  name: external-secrets-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
